### ISSUE TITLE
Symbols Override font

### ISSUE THREAD

**Issue by indrora** [ryanoasis/powerline-extra-symbols#1]
Powerline uses a font called Powerline Symbols which can be used as a "preferred" font-family in `fontconfig`.

This "override" font would be helpful, or a way to "generate" this font would be rather neat.

**Comment by ryanoasis** [comment]
@indrora Yep I plan to get this into a 'Powerline Symbols' font (that just has the glyphs) but I started in a font with a different em size so I will need to do some scaling. Thanks

I don't have a lot of experience with `fontconfig` because I have mostly just done patching

**Comment by indrora** [comment]
Fontconfig is really easy. I've implemented it in [my dotfiles](https://bitbucket.org/indrora/dotfiles/src/2afdaa0fa8c79c7e0fb272e7cf5ad2892cb78338/powerline_fonts.sh?at=master) as a fetch script.

**Comment by ryanoasis** [comment]
Ah okay yep. Thanks.

Not sure when I will get to generating an updated powerline symbols font but I will let you know :smile:

**Comment by zeorin** [comment]
+1 Would like a separate powerline-extra-symbols font, as per powerline's own separate font.

**Comment by ryanoasis** [comment]
I think I am going to consider this done for now.

Reasoning:
- since fda178d1c11be2f451f96df637084d3e59e8c0b0 the separate [PowerlineExtraSymbols.otf](https://github.com/ryanoasis/powerline-extra-symbols/blob/master/PowerlineExtraSymbols.otf) has been available
- You can use the above font for creating an override with `fontconfig`
- Also available now is an actual [Nerd Fonts `fontconfig`](https://github.com/ryanoasis/nerd-fonts/blob/master/10-nerd-font-symbols.conf) which includes the extra powerline glyphs :smile:
